title: 'Graficación & Animación'
default_lang: es
author:
  name: 'Claudia Caicedo'
  email: claudia.sce@gmail.com
  url: 'http://getgrav.org/'
  gravatar: contact@getgrav.org
  description: 'Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.'
taxonomies:
  - category
  - tag
  - month
summary:
  enabled: true
  format: short
  size: 100
  delimiter: '==='
  striptags: true
blog:
  route: ''
description: 'Graficación & Animación'
global_featured_image: featured.jpg
social:
  -
    text: facebook
    url: 'http://www.facebook.com/getgrav'
  -
    text: twitter
    url: 'http://www.twitter.com/getgrav'
  -
    text: youtube-play
    url: 'http://www.youtube.com/getgrav'
slider:
  -
    image: slide3.jpg
    title: 'Graficación & Animación'
    url: '#'
  -
    image: slide1.jpg
    title: 'Html, CSS y JavaScript'
    url: '#'
  -
    image: slide2.jpg
    title: Docker
    url: '#'
menu:
  -
    url: error
    text: 'Error Page'
