enabled: true
dropdown:
  enabled: true
year: 0
social_twitter: 'https://twitter.com/Claudia_SCe'
social_facebook: 'https://www.facebook.com/claudia.caicedo.7524'
social_github: 'https://github.com/claudiacaicedo'
