streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/quark-open-publishing, user/themes/quark]
chromeless:
  enabled: false
display_of_git_sync_repo_link: none
type_of_git_sync_repo_link: view
h5pembedrootpath: 'https://h5p.org/h5p/embed/'
cc_license:
  enabled: false
  type: ccby
  icon: false
dropdown:
  enabled: false
displaycustommenus:
  enabled: false
hidehomemenulink: false
production-mode: false
header-fixed: true
header-animated: true
header-dark: false
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
